using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MakeMKV_Title_Decoder.Util
{
    public struct LanguageCode
    {
        public readonly string Code;
        public readonly string Name;
        public readonly bool IsBibliographic;
        public readonly bool IsTerminology;

        public LanguageCode(string code, string name, bool isBibliographic, bool isTerminology)
        {
            this.Code = code;
            this.Name = name;
            this.IsBibliographic = isBibliographic;
            this.IsTerminology = isTerminology;
        }

        public override string ToString()
        {
            string result = Name;
            List<string> extras = new();
            if (IsBibliographic)
            {
                extras.Add("Bibliographic");
            }
            if (IsTerminology)
            {
                extras.Add("Terminology");
            }
            string append = "";
            if (extras.Count > 0)
            {
                append = " (" + string.Join(", ", extras) + ")";
            }
            return Name + append;
        }
    }

    internal static class Languages
    {

        static readonly Dictionary<string, LanguageCode> LanguageLookup = new Dictionary<string, LanguageCode>() {
            {"aar", new("aar", "Afar", false, false) },
            {"abk", new("abk", "Abkhazian", false, false) },
            {"ace", new("ace", "Achinese", false, false) },
            {"ach", new("ach", "Acoli", false, false) },
            {"ada", new("ada", "Adangme", false, false) },
            {"ady", new("ady", "Adyghe; Adygei", false, false) },
            {"afa", new("afa", "Afro-Asiatic languages", false, false) },
            {"afh", new("afh", "Afrihili", false, false) },
            {"afr", new("afr", "Afrikaans", false, false) },
            {"ain", new("ain", "Ainu", false, false) },
            {"aka", new("aka", "Akan", false, false) },
            {"akk", new("akk", "Akkadian", false, false) },
            {"alb", new("alb", "Albanian", true, false) },
            {"sqi", new("sqi", "Albanian", false, true) },
            {"ale", new("ale", "Aleut", false, false) },
            {"alg", new("alg", "Algonquian languages", false, false) },
            {"alt", new("alt", "Southern Altai", false, false) },
            {"amh", new("amh", "Amharic", false, false) },
            {"ang", new("ang", "English, Old (ca.450-1100)", false, false) },
            {"anp", new("anp", "Angika", false, false) },
            {"apa", new("apa", "Apache languages", false, false) },
            {"ara", new("ara", "Arabic", false, false) },
            {"arc", new("arc", "Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)", false, false) },
            {"arg", new("arg", "Aragonese", false, false) },
            {"arm", new("arm", "Armenian", true, false) },
            {"hye", new("hye", "Armenian", false, true) },
            {"arn", new("arn", "Mapudungun; Mapuche", false, false) },
            {"arp", new("arp", "Arapaho", false, false) },
            {"art", new("art", "Artificial languages", false, false) },
            {"arw", new("arw", "Arawak", false, false) },
            {"asm", new("asm", "Assamese", false, false) },
            {"ast", new("ast", "Asturian; Bable; Leonese; Asturleonese", false, false) },
            {"ath", new("ath", "Athapascan languages", false, false) },
            {"aus", new("aus", "Australian languages", false, false) },
            {"ava", new("ava", "Avaric", false, false) },
            {"ave", new("ave", "Avestan", false, false) },
            {"awa", new("awa", "Awadhi", false, false) },
            {"aym", new("aym", "Aymara", false, false) },
            {"aze", new("aze", "Azerbaijani", false, false) },
            {"bad", new("bad", "Banda languages", false, false) },
            {"bai", new("bai", "Bamileke languages", false, false) },
            {"bak", new("bak", "Bashkir", false, false) },
            {"bal", new("bal", "Baluchi", false, false) },
            {"bam", new("bam", "Bambara", false, false) },
            {"ban", new("ban", "Balinese", false, false) },
            {"baq", new("baq", "Basque", true, false) },
            {"eus", new("eus", "Basque", false, true) },
            {"bas", new("bas", "Basa", false, false) },
            {"bat", new("bat", "Baltic languages", false, false) },
            {"bej", new("bej", "Beja; Bedawiyet", false, false) },
            {"bel", new("bel", "Belarusian", false, false) },
            {"bem", new("bem", "Bemba", false, false) },
            {"ben", new("ben", "Bengali", false, false) },
            {"ber", new("ber", "Berber languages", false, false) },
            {"bho", new("bho", "Bhojpuri", false, false) },
            {"bih", new("bih", "Bihari languages", false, false) },
            {"bik", new("bik", "Bikol", false, false) },
            {"bin", new("bin", "Bini; Edo", false, false) },
            {"bis", new("bis", "Bislama", false, false) },
            {"bla", new("bla", "Siksika", false, false) },
            {"bnt", new("bnt", "Bantu languages", false, false) },
            {"bos", new("bos", "Bosnian", false, false) },
            {"bra", new("bra", "Braj", false, false) },
            {"bre", new("bre", "Breton", false, false) },
            {"btk", new("btk", "Batak languages", false, false) },
            {"bua", new("bua", "Buriat", false, false) },
            {"bug", new("bug", "Buginese", false, false) },
            {"bul", new("bul", "Bulgarian", false, false) },
            {"bur", new("bur", "Burmese", true, false) },
            {"mya", new("mya", "Burmese", false, true) },
            {"byn", new("byn", "Blin; Bilin", false, false) },
            {"cad", new("cad", "Caddo", false, false) },
            {"cai", new("cai", "Central American Indian languages", false, false) },
            {"car", new("car", "Galibi Carib", false, false) },
            {"cat", new("cat", "Catalan; Valencian", false, false) },
            {"cau", new("cau", "Caucasian languages", false, false) },
            {"ceb", new("ceb", "Cebuano", false, false) },
            {"cel", new("cel", "Celtic languages", false, false) },
            {"cha", new("cha", "Chamorro", false, false) },
            {"chb", new("chb", "Chibcha", false, false) },
            {"che", new("che", "Chechen", false, false) },
            {"chg", new("chg", "Chagatai", false, false) },
            {"chi", new("chi", "Chinese", true, false) },
            {"zho", new("zho", "Chinese", false, true) },
            {"chk", new("chk", "Chuukese", false, false) },
            {"chm", new("chm", "Mari", false, false) },
            {"chn", new("chn", "Chinook jargon", false, false) },
            {"cho", new("cho", "Choctaw", false, false) },
            {"chp", new("chp", "Chipewyan; Dene Suline", false, false) },
            {"chr", new("chr", "Cherokee", false, false) },
            {"chu", new("chu", "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic", false, false) },
            {"chv", new("chv", "Chuvash", false, false) },
            {"chy", new("chy", "Cheyenne", false, false) },
            {"cmc", new("cmc", "Chamic languages", false, false) },
            {"cnr", new("cnr", "Montenegrin", false, false) },
            {"cop", new("cop", "Coptic", false, false) },
            {"cor", new("cor", "Cornish", false, false) },
            {"cos", new("cos", "Corsican", false, false) },
            {"cpe", new("cpe", "Creoles and pidgins, English based", false, false) },
            {"cpf", new("cpf", "Creoles and pidgins, French-based", false, false) },
            {"cpp", new("cpp", "Creoles and pidgins, Portuguese-based", false, false) },
            {"cre", new("cre", "Cree", false, false) },
            {"crh", new("crh", "Crimean Tatar; Crimean Turkish", false, false) },
            {"crp", new("crp", "Creoles and pidgins", false, false) },
            {"csb", new("csb", "Kashubian", false, false) },
            {"cus", new("cus", "Cushitic languages", false, false) },
            {"cze", new("cze", "Czech", true, false) },
            {"ces", new("ces", "Czech", false, true) },
            {"dak", new("dak", "Dakota", false, false) },
            {"dan", new("dan", "Danish", false, false) },
            {"dar", new("dar", "Dargwa", false, false) },
            {"day", new("day", "Land Dayak languages", false, false) },
            {"del", new("del", "Delaware", false, false) },
            {"den", new("den", "Slave (Athapascan)", false, false) },
            {"dgr", new("dgr", "Tlicho; Dogrib", false, false) },
            {"din", new("din", "Dinka", false, false) },
            {"div", new("div", "Divehi; Dhivehi; Maldivian", false, false) },
            {"doi", new("doi", "Dogri", false, false) },
            {"dra", new("dra", "Dravidian languages", false, false) },
            {"dsb", new("dsb", "Lower Sorbian", false, false) },
            {"dua", new("dua", "Duala", false, false) },
            {"dum", new("dum", "Dutch, Middle (ca.1050-1350)", false, false) },
            {"dut", new("dut", "Dutch; Flemish", true, false) },
            {"nld", new("nld", "Dutch; Flemish", false, true) },
            {"dyu", new("dyu", "Dyula", false, false) },
            {"dzo", new("dzo", "Dzongkha", false, false) },
            {"efi", new("efi", "Efik", false, false) },
            {"egy", new("egy", "Egyptian (Ancient)", false, false) },
            {"eka", new("eka", "Ekajuk", false, false) },
            {"elx", new("elx", "Elamite", false, false) },
            {"eng", new("eng", "English", false, false) },
            {"enm", new("enm", "English, Middle (1100-1500)", false, false) },
            {"epo", new("epo", "Esperanto", false, false) },
            {"est", new("est", "Estonian", false, false) },
            {"ewe", new("ewe", "Ewe", false, false) },
            {"ewo", new("ewo", "Ewondo", false, false) },
            {"fan", new("fan", "Fang", false, false) },
            {"fao", new("fao", "Faroese", false, false) },
            {"fat", new("fat", "Fanti", false, false) },
            {"fij", new("fij", "Fijian", false, false) },
            {"fil", new("fil", "Filipino; Pilipino", false, false) },
            {"fin", new("fin", "Finnish", false, false) },
            {"fiu", new("fiu", "Finno-Ugrian languages", false, false) },
            {"fon", new("fon", "Fon", false, false) },
            {"fre", new("fre", "French", true, false) },
            {"fra", new("fra", "French", false, true) },
            {"frm", new("frm", "French, Middle (ca.1400-1600)", false, false) },
            {"fro", new("fro", "French, Old (842-ca.1400)", false, false) },
            {"frr", new("frr", "Northern Frisian", false, false) },
            {"frs", new("frs", "Eastern Frisian", false, false) },
            {"fry", new("fry", "Western Frisian", false, false) },
            {"ful", new("ful", "Fulah", false, false) },
            {"fur", new("fur", "Friulian", false, false) },
            {"gaa", new("gaa", "Ga", false, false) },
            {"gay", new("gay", "Gayo", false, false) },
            {"gba", new("gba", "Gbaya", false, false) },
            {"gem", new("gem", "Germanic languages", false, false) },
            {"geo", new("geo", "Georgian", true, false) },
            {"kat", new("kat", "Georgian", false, true) },
            {"ger", new("ger", "German", true, false) },
            {"deu", new("deu", "German", false, true) },
            {"gez", new("gez", "Geez", false, false) },
            {"gil", new("gil", "Gilbertese", false, false) },
            {"gla", new("gla", "Gaelic; Scottish Gaelic", false, false) },
            {"gle", new("gle", "Irish", false, false) },
            {"glg", new("glg", "Galician", false, false) },
            {"glv", new("glv", "Manx", false, false) },
            {"gmh", new("gmh", "German, Middle High (ca.1050-1500)", false, false) },
            {"goh", new("goh", "German, Old High (ca.750-1050)", false, false) },
            {"gon", new("gon", "Gondi", false, false) },
            {"gor", new("gor", "Gorontalo", false, false) },
            {"got", new("got", "Gothic", false, false) },
            {"grb", new("grb", "Grebo", false, false) },
            {"grc", new("grc", "Greek, Ancient (to 1453)", false, false) },
            {"gre", new("gre", "Greek, Modern (1453-)", true, false) },
            {"ell", new("ell", "Greek, Modern (1453-)", false, true) },
            {"grn", new("grn", "Guarani", false, false) },
            {"gsw", new("gsw", "Swiss German; Alemannic; Alsatian", false, false) },
            {"guj", new("guj", "Gujarati", false, false) },
            {"gwi", new("gwi", "Gwich'in", false, false) },
            {"hai", new("hai", "Haida", false, false) },
            {"hat", new("hat", "Haitian; Haitian Creole", false, false) },
            {"hau", new("hau", "Hausa", false, false) },
            {"haw", new("haw", "Hawaiian", false, false) },
            {"heb", new("heb", "Hebrew", false, false) },
            {"her", new("her", "Herero", false, false) },
            {"hil", new("hil", "Hiligaynon", false, false) },
            {"him", new("him", "Himachali languages; Western Pahari languages", false, false) },
            {"hin", new("hin", "Hindi", false, false) },
            {"hit", new("hit", "Hittite", false, false) },
            {"hmn", new("hmn", "Hmong; Mong", false, false) },
            {"hmo", new("hmo", "Hiri Motu", false, false) },
            {"hrv", new("hrv", "Croatian", false, false) },
            {"hsb", new("hsb", "Upper Sorbian", false, false) },
            {"hun", new("hun", "Hungarian", false, false) },
            {"hup", new("hup", "Hupa", false, false) },
            {"iba", new("iba", "Iban", false, false) },
            {"ibo", new("ibo", "Igbo", false, false) },
            {"ice", new("ice", "Icelandic", true, false) },
            {"isl", new("isl", "Icelandic", false, true) },
            {"ido", new("ido", "Ido", false, false) },
            {"iii", new("iii", "Sichuan Yi; Nuosu", false, false) },
            {"ijo", new("ijo", "Ijo languages", false, false) },
            {"iku", new("iku", "Inuktitut", false, false) },
            {"ile", new("ile", "Interlingue; Occidental", false, false) },
            {"ilo", new("ilo", "Iloko", false, false) },
            {"ina", new("ina", "Interlingua (International Auxiliary Language Association)", false, false) },
            {"inc", new("inc", "Indic languages", false, false) },
            {"ind", new("ind", "Indonesian", false, false) },
            {"ine", new("ine", "Indo-European languages", false, false) },
            {"inh", new("inh", "Ingush", false, false) },
            {"ipk", new("ipk", "Inupiaq", false, false) },
            {"ira", new("ira", "Iranian languages", false, false) },
            {"iro", new("iro", "Iroquoian languages", false, false) },
            {"ita", new("ita", "Italian", false, false) },
            {"jav", new("jav", "Javanese", false, false) },
            {"jbo", new("jbo", "Lojban", false, false) },
            {"jpn", new("jpn", "Japanese", false, false) },
            {"jpr", new("jpr", "Judeo-Persian", false, false) },
            {"jrb", new("jrb", "Judeo-Arabic", false, false) },
            {"kaa", new("kaa", "Kara-Kalpak", false, false) },
            {"kab", new("kab", "Kabyle", false, false) },
            {"kac", new("kac", "Kachin; Jingpho", false, false) },
            {"kal", new("kal", "Kalaallisut; Greenlandic", false, false) },
            {"kam", new("kam", "Kamba", false, false) },
            {"kan", new("kan", "Kannada", false, false) },
            {"kar", new("kar", "Karen languages", false, false) },
            {"kas", new("kas", "Kashmiri", false, false) },
            {"kau", new("kau", "Kanuri", false, false) },
            {"kaw", new("kaw", "Kawi", false, false) },
            {"kaz", new("kaz", "Kazakh", false, false) },
            {"kbd", new("kbd", "Kabardian", false, false) },
            {"kha", new("kha", "Khasi", false, false) },
            {"khi", new("khi", "Khoisan languages", false, false) },
            {"khm", new("khm", "Central Khmer", false, false) },
            {"kho", new("kho", "Khotanese; Sakan", false, false) },
            {"kik", new("kik", "Kikuyu; Gikuyu", false, false) },
            {"kin", new("kin", "Kinyarwanda", false, false) },
            {"kir", new("kir", "Kirghiz; Kyrgyz", false, false) },
            {"kmb", new("kmb", "Kimbundu", false, false) },
            {"kok", new("kok", "Konkani", false, false) },
            {"kom", new("kom", "Komi", false, false) },
            {"kon", new("kon", "Kongo", false, false) },
            {"kor", new("kor", "Korean", false, false) },
            {"kos", new("kos", "Kosraean", false, false) },
            {"kpe", new("kpe", "Kpelle", false, false) },
            {"krc", new("krc", "Karachay-Balkar", false, false) },
            {"krl", new("krl", "Karelian", false, false) },
            {"kro", new("kro", "Kru languages", false, false) },
            {"kru", new("kru", "Kurukh", false, false) },
            {"kua", new("kua", "Kuanyama; Kwanyama", false, false) },
            {"kum", new("kum", "Kumyk", false, false) },
            {"kur", new("kur", "Kurdish", false, false) },
            {"kut", new("kut", "Kutenai", false, false) },
            {"lad", new("lad", "Ladino", false, false) },
            {"lah", new("lah", "Lahnda", false, false) },
            {"lam", new("lam", "Lamba", false, false) },
            {"lao", new("lao", "Lao", false, false) },
            {"lat", new("lat", "Latin", false, false) },
            {"lav", new("lav", "Latvian", false, false) },
            {"lez", new("lez", "Lezghian", false, false) },
            {"lim", new("lim", "Limburgan; Limburger; Limburgish", false, false) },
            {"lin", new("lin", "Lingala", false, false) },
            {"lit", new("lit", "Lithuanian", false, false) },
            {"lol", new("lol", "Mongo", false, false) },
            {"loz", new("loz", "Lozi", false, false) },
            {"ltz", new("ltz", "Luxembourgish; Letzeburgesch", false, false) },
            {"lua", new("lua", "Luba-Lulua", false, false) },
            {"lub", new("lub", "Luba-Katanga", false, false) },
            {"lug", new("lug", "Ganda", false, false) },
            {"lui", new("lui", "Luiseno", false, false) },
            {"lun", new("lun", "Lunda", false, false) },
            {"luo", new("luo", "Luo (Kenya and Tanzania)", false, false) },
            {"lus", new("lus", "Lushai", false, false) },
            {"mac", new("mac", "Macedonian", true, false) },
            {"mkd", new("mkd", "Macedonian", false, true) },
            {"mad", new("mad", "Madurese", false, false) },
            {"mag", new("mag", "Magahi", false, false) },
            {"mah", new("mah", "Marshallese", false, false) },
            {"mai", new("mai", "Maithili", false, false) },
            {"mak", new("mak", "Makasar", false, false) },
            {"mal", new("mal", "Malayalam", false, false) },
            {"man", new("man", "Mandingo", false, false) },
            {"mao", new("mao", "Maori", true, false) },
            {"mri", new("mri", "Maori", false, true) },
            {"map", new("map", "Austronesian languages", false, false) },
            {"mar", new("mar", "Marathi", false, false) },
            {"mas", new("mas", "Masai", false, false) },
            {"may", new("may", "Malay", true, false) },
            {"msa", new("msa", "Malay", false, true) },
            {"mdf", new("mdf", "Moksha", false, false) },
            {"mdr", new("mdr", "Mandar", false, false) },
            {"men", new("men", "Mende", false, false) },
            {"mga", new("mga", "Irish, Middle (900-1200)", false, false) },
            {"mic", new("mic", "Mi'kmaq; Micmac", false, false) },
            {"min", new("min", "Minangkabau", false, false) },
            {"mis", new("mis", "Uncoded languages", false, false) },
            {"mkh", new("mkh", "Mon-Khmer languages", false, false) },
            {"mlg", new("mlg", "Malagasy", false, false) },
            {"mlt", new("mlt", "Maltese", false, false) },
            {"mnc", new("mnc", "Manchu", false, false) },
            {"mni", new("mni", "Manipuri", false, false) },
            {"mno", new("mno", "Manobo languages", false, false) },
            {"moh", new("moh", "Mohawk", false, false) },
            {"mon", new("mon", "Mongolian", false, false) },
            {"mos", new("mos", "Mossi", false, false) },
            {"mul", new("mul", "Multiple languages", false, false) },
            {"mun", new("mun", "Munda languages", false, false) },
            {"mus", new("mus", "Creek", false, false) },
            {"mwl", new("mwl", "Mirandese", false, false) },
            {"mwr", new("mwr", "Marwari", false, false) },
            {"myn", new("myn", "Mayan languages", false, false) },
            {"myv", new("myv", "Erzya", false, false) },
            {"nah", new("nah", "Nahuatl languages", false, false) },
            {"nai", new("nai", "North American Indian languages", false, false) },
            {"nap", new("nap", "Neapolitan", false, false) },
            {"nau", new("nau", "Nauru", false, false) },
            {"nav", new("nav", "Navajo; Navaho", false, false) },
            {"nbl", new("nbl", "Ndebele, South; South Ndebele", false, false) },
            {"nde", new("nde", "Ndebele, North; North Ndebele", false, false) },
            {"ndo", new("ndo", "Ndonga", false, false) },
            {"nds", new("nds", "Low German; Low Saxon; German, Low; Saxon, Low", false, false) },
            {"nep", new("nep", "Nepali", false, false) },
            {"new", new("new", "Nepal Bhasa; Newari", false, false) },
            {"nia", new("nia", "Nias", false, false) },
            {"nic", new("nic", "Niger-Kordofanian languages", false, false) },
            {"niu", new("niu", "Niuean", false, false) },
            {"nno", new("nno", "Norwegian Nynorsk; Nynorsk, Norwegian", false, false) },
            {"nob", new("nob", "Bokmål, Norwegian; Norwegian Bokmål", false, false) },
            {"nog", new("nog", "Nogai", false, false) },
            {"non", new("non", "Norse, Old", false, false) },
            {"nor", new("nor", "Norwegian", false, false) },
            {"nqo", new("nqo", "N'Ko", false, false) },
            {"nso", new("nso", "Pedi; Sepedi; Northern Sotho", false, false) },
            {"nub", new("nub", "Nubian languages", false, false) },
            {"nwc", new("nwc", "Classical Newari; Old Newari; Classical Nepal Bhasa", false, false) },
            {"nya", new("nya", "Chichewa; Chewa; Nyanja", false, false) },
            {"nym", new("nym", "Nyamwezi", false, false) },
            {"nyn", new("nyn", "Nyankole", false, false) },
            {"nyo", new("nyo", "Nyoro", false, false) },
            {"nzi", new("nzi", "Nzima", false, false) },
            {"oci", new("oci", "Occitan (post 1500)", false, false) },
            {"oji", new("oji", "Ojibwa", false, false) },
            {"ori", new("ori", "Oriya", false, false) },
            {"orm", new("orm", "Oromo", false, false) },
            {"osa", new("osa", "Osage", false, false) },
            {"oss", new("oss", "Ossetian; Ossetic", false, false) },
            {"ota", new("ota", "Turkish, Ottoman (1500-1928)", false, false) },
            {"oto", new("oto", "Otomian languages", false, false) },
            {"paa", new("paa", "Papuan languages", false, false) },
            {"pag", new("pag", "Pangasinan", false, false) },
            {"pal", new("pal", "Pahlavi", false, false) },
            {"pam", new("pam", "Pampanga; Kapampangan", false, false) },
            {"pan", new("pan", "Panjabi; Punjabi", false, false) },
            {"pap", new("pap", "Papiamento", false, false) },
            {"pau", new("pau", "Palauan", false, false) },
            {"peo", new("peo", "Persian, Old (ca.600-400 B.C.)", false, false) },
            {"per", new("per", "Persian", true, false) },
            {"fas", new("fas", "Persian", false, true) },
            {"phi", new("phi", "Philippine languages", false, false) },
            {"phn", new("phn", "Phoenician", false, false) },
            {"pli", new("pli", "Pali", false, false) },
            {"pol", new("pol", "Polish", false, false) },
            {"pon", new("pon", "Pohnpeian", false, false) },
            {"por", new("por", "Portuguese", false, false) },
            {"pra", new("pra", "Prakrit languages", false, false) },
            {"pro", new("pro", "Provençal, Old (to 1500); Occitan, Old (to 1500)", false, false) },
            {"pus", new("pus", "Pushto; Pashto", false, false) },
            {"qaa-qtz", new("qaa-qtz", "Reserved for local use", false, false) },
            {"que", new("que", "Quechua", false, false) },
            {"raj", new("raj", "Rajasthani", false, false) },
            {"rap", new("rap", "Rapanui", false, false) },
            {"rar", new("rar", "Rarotongan; Cook Islands Maori", false, false) },
            {"roa", new("roa", "Romance languages", false, false) },
            {"roh", new("roh", "Romansh", false, false) },
            {"rom", new("rom", "Romany", false, false) },
            {"rum", new("rum", "Romanian; Moldavian; Moldovan", true, false) },
            {"ron", new("ron", "Romanian; Moldavian; Moldovan", false, true) },
            {"run", new("run", "Rundi", false, false) },
            {"rup", new("rup", "Aromanian; Arumanian; Macedo-Romanian", false, false) },
            {"rus", new("rus", "Russian", false, false) },
            {"sad", new("sad", "Sandawe", false, false) },
            {"sag", new("sag", "Sango", false, false) },
            {"sah", new("sah", "Yakut", false, false) },
            {"sai", new("sai", "South American Indian languages", false, false) },
            {"sal", new("sal", "Salishan languages", false, false) },
            {"sam", new("sam", "Samaritan Aramaic", false, false) },
            {"san", new("san", "Sanskrit", false, false) },
            {"sas", new("sas", "Sasak", false, false) },
            {"sat", new("sat", "Santali", false, false) },
            {"scn", new("scn", "Sicilian", false, false) },
            {"sco", new("sco", "Scots", false, false) },
            {"sel", new("sel", "Selkup", false, false) },
            {"sem", new("sem", "Semitic languages", false, false) },
            {"sga", new("sga", "Irish, Old (to 900)", false, false) },
            {"sgn", new("sgn", "Sign Languages", false, false) },
            {"shn", new("shn", "Shan", false, false) },
            {"sid", new("sid", "Sidamo", false, false) },
            {"sin", new("sin", "Sinhala; Sinhalese", false, false) },
            {"sio", new("sio", "Siouan languages", false, false) },
            {"sit", new("sit", "Sino-Tibetan languages", false, false) },
            {"sla", new("sla", "Slavic languages", false, false) },
            {"slo", new("slo", "Slovak", true, false) },
            {"slk", new("slk", "Slovak", false, true) },
            {"slv", new("slv", "Slovenian", false, false) },
            {"sma", new("sma", "Southern Sami", false, false) },
            {"sme", new("sme", "Northern Sami", false, false) },
            {"smi", new("smi", "Sami languages", false, false) },
            {"smj", new("smj", "Lule Sami", false, false) },
            {"smn", new("smn", "Inari Sami", false, false) },
            {"smo", new("smo", "Samoan", false, false) },
            {"sms", new("sms", "Skolt Sami", false, false) },
            {"sna", new("sna", "Shona", false, false) },
            {"snd", new("snd", "Sindhi", false, false) },
            {"snk", new("snk", "Soninke", false, false) },
            {"sog", new("sog", "Sogdian", false, false) },
            {"som", new("som", "Somali", false, false) },
            {"son", new("son", "Songhai languages", false, false) },
            {"sot", new("sot", "Sotho, Southern", false, false) },
            {"spa", new("spa", "Spanish; Castilian", false, false) },
            {"srd", new("srd", "Sardinian", false, false) },
            {"srn", new("srn", "Sranan Tongo", false, false) },
            {"srp", new("srp", "Serbian", false, false) },
            {"srr", new("srr", "Serer", false, false) },
            {"ssa", new("ssa", "Nilo-Saharan languages", false, false) },
            {"ssw", new("ssw", "Swati", false, false) },
            {"suk", new("suk", "Sukuma", false, false) },
            {"sun", new("sun", "Sundanese", false, false) },
            {"sus", new("sus", "Susu", false, false) },
            {"sux", new("sux", "Sumerian", false, false) },
            {"swa", new("swa", "Swahili", false, false) },
            {"swe", new("swe", "Swedish", false, false) },
            {"syc", new("syc", "Classical Syriac", false, false) },
            {"syr", new("syr", "Syriac", false, false) },
            {"tah", new("tah", "Tahitian", false, false) },
            {"tai", new("tai", "Tai languages", false, false) },
            {"tam", new("tam", "Tamil", false, false) },
            {"tat", new("tat", "Tatar", false, false) },
            {"tel", new("tel", "Telugu", false, false) },
            {"tem", new("tem", "Timne", false, false) },
            {"ter", new("ter", "Tereno", false, false) },
            {"tet", new("tet", "Tetum", false, false) },
            {"tgk", new("tgk", "Tajik", false, false) },
            {"tgl", new("tgl", "Tagalog", false, false) },
            {"tha", new("tha", "Thai", false, false) },
            {"tib", new("tib", "Tibetan", true, false) },
            {"bod", new("bod", "Tibetan", false, true) },
            {"tig", new("tig", "Tigre", false, false) },
            {"tir", new("tir", "Tigrinya", false, false) },
            {"tiv", new("tiv", "Tiv", false, false) },
            {"tkl", new("tkl", "Tokelau", false, false) },
            {"tlh", new("tlh", "Klingon; tlhIngan-Hol", false, false) },
            {"tli", new("tli", "Tlingit", false, false) },
            {"tmh", new("tmh", "Tamashek", false, false) },
            {"tog", new("tog", "Tonga (Nyasa)", false, false) },
            {"ton", new("ton", "Tonga (Tonga Islands)", false, false) },
            {"tpi", new("tpi", "Tok Pisin", false, false) },
            {"tsi", new("tsi", "Tsimshian", false, false) },
            {"tsn", new("tsn", "Tswana", false, false) },
            {"tso", new("tso", "Tsonga", false, false) },
            {"tuk", new("tuk", "Turkmen", false, false) },
            {"tum", new("tum", "Tumbuka", false, false) },
            {"tup", new("tup", "Tupi languages", false, false) },
            {"tur", new("tur", "Turkish", false, false) },
            {"tut", new("tut", "Altaic languages", false, false) },
            {"tvl", new("tvl", "Tuvalu", false, false) },
            {"twi", new("twi", "Twi", false, false) },
            {"tyv", new("tyv", "Tuvinian", false, false) },
            {"udm", new("udm", "Udmurt", false, false) },
            {"uga", new("uga", "Ugaritic", false, false) },
            {"uig", new("uig", "Uighur; Uyghur", false, false) },
            {"ukr", new("ukr", "Ukrainian", false, false) },
            {"umb", new("umb", "Umbundu", false, false) },
            {"und", new("und", "Undetermined", false, false) },
            {"urd", new("urd", "Urdu", false, false) },
            {"uzb", new("uzb", "Uzbek", false, false) },
            {"vai", new("vai", "Vai", false, false) },
            {"ven", new("ven", "Venda", false, false) },
            {"vie", new("vie", "Vietnamese", false, false) },
            {"vol", new("vol", "Volapük", false, false) },
            {"vot", new("vot", "Votic", false, false) },
            {"wak", new("wak", "Wakashan languages", false, false) },
            {"wal", new("wal", "Wolaitta; Wolaytta", false, false) },
            {"war", new("war", "Waray", false, false) },
            {"was", new("was", "Washo", false, false) },
            {"wel", new("wel", "Welsh", true, false) },
            {"cym", new("cym", "Welsh", false, true) },
            {"wen", new("wen", "Sorbian languages", false, false) },
            {"wln", new("wln", "Walloon", false, false) },
            {"wol", new("wol", "Wolof", false, false) },
            {"xal", new("xal", "Kalmyk; Oirat", false, false) },
            {"xho", new("xho", "Xhosa", false, false) },
            {"yao", new("yao", "Yao", false, false) },
            {"yap", new("yap", "Yapese", false, false) },
            {"yid", new("yid", "Yiddish", false, false) },
            {"yor", new("yor", "Yoruba", false, false) },
            {"ypk", new("ypk", "Yupik languages", false, false) },
            {"zap", new("zap", "Zapotec", false, false) },
            {"zbl", new("zbl", "Blissymbols; Blissymbolics; Bliss", false, false) },
            {"zen", new("zen", "Zenaga", false, false) },
            {"zgh", new("zgh", "Standard Moroccan Tamazight", false, false) },
            {"zha", new("zha", "Zhuang; Chuang", false, false) },
            {"znd", new("znd", "Zande languages", false, false) },
            {"zul", new("zul", "Zulu", false, false) },
            {"zun", new("zun", "Zuni", false, false) },
            {"zxx", new("zxx", "No linguistic content; Not applicable", false, false) },
            {"zza", new("zza", "Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki", false, false) },
        };

        public static bool IsValidLanguageCode(string lang)
        {
            lang = lang.ToLower();
            return LanguageLookup.ContainsKey(lang);
        }

        public static IEnumerable<LanguageCode> GetAllLanguages()
        {
            return LanguageLookup.Values;
        }
    }
}
